#!/bin/bash

# a sourcable setup for the test environment

setup() {
    if [[ $1 =~ ^/ ]] ; then
	mydir=$1
    else
	mydir=`pwd`/$1
    fi
    mydir=$1
    export PATH=$mydir/bin:`dirname $mydir`/bin:$PATH
    export HOME=$mydir/output/interactive/home
    export MOCKSERVERS=$mydir/output/interactive/mock-servers
    mkdir -p $HOME
    PS1="testing$ "
}
